#!/usr/bin/env bash

function main {
  if [[ "$#" -gt 0 ]]; then
    exec "$@"
  else
    install -d -o ubuntu -g ubuntu -m 0700 /home/ubuntu/.ssh
    install -o ubuntu -g ubuntu -m 0600 /data/authorized_keys /home/ubuntu/.ssh/authorized_keys

    mkdir -p /var/run/sshd
    exec /usr/sbin/sshd -D -o UseDNS=no -o UsePAM=yes -o PasswordAuthentication=no -o UsePrivilegeSeparation=sandbox
  fi
}

main "$@"
